[package]
name = "program"
version = "0.0.1"
authors = ["mithraiclabs", "tomjohn1028"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []
program = ["solana-sdk/program"]
default = ["solana-sdk/default"]

[dependencies]
solana-program = "1.4.4"
arrayref = "0.3.6"

[dev-dependencies]
solana-sdk = "1.4.4"

[lib]
name = "solana_bpf_program"
crate-type = ["cdylib", "lib"]
